-- Configuração dos comandos do LSP
vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, bufopts)
vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, bufopts)
vim.keymap.set('n', '<C-n>', vim.lsp.diagnostic.goto_prev, bufopts)
vim.keymap.set('n', '<C-p>', vim.lsp.diagnostic.goto_next, bufopts)
vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, bufopts)
vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, bufopts)
vim.keymap.set('n', '<space>wl', function()
  print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
end, bufopts)
vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, bufopts)
vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, bufopts)
vim.keymap.set('n', '<space>ca', vim.lsp.buf.code_action, bufopts)
vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
vim.keymap.set('n', '<space>f', vim.lsp.buf.formatting, bufopts)

vim.keymap.set('n', '<C-S>', ':update<CR>', bufopts)
vim.keymap.set('v', '<C-S>', '<C-C>:update<CR>', bufopts)
vim.keymap.set('i', '<C-S>', '<C-O>:update<CR>', bufopts)

vim.keymap.set('n', '<C-right>', 'w', bufopts)
vim.keymap.set('v', '<C-right>', 'w', bufopts)
vim.keymap.set('i', '<C-right>', '<C-O>w', bufopts)

vim.keymap.set('n', '<C-left>', 'b', bufopts)
vim.keymap.set('v', '<C-left>', 'b', bufopts)
vim.keymap.set('i', '<C-left>', '<C-O>b', bufopts)
